name: Integration tests

on:
  pull_request:

env:
  ACALA_PROD_AUTH_TOKEN: 'token'
  ACALA_TEST_AUTH_TOKEN: 'token'
  MOONBEAM_PROD_AUTH_TOKEN: 'token'
  MOONBEAM_TEST_AUTH_TOKEN: 'token'
  MOONPAY_PRODUCTION_SECRET: 'token'
  MOONPAY_TEST_SECRET: 'token'
  MERCURYO_PRODUCTION_SECRET: 'token'
  MERCURYO_TEST_SECRET: 'token'
  EHTERSCAN_API_KEY_MOONBEAM: 'token'
  EHTERSCAN_API_KEY_MOONRIVER=: 'token'

  CI_KEYSTORE_PASS: 'token'
  CI_KEYSTORE_KEY_ALIAS: 'token'
  CI_KEYSTORE_KEY_PASS: 'token'

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@master

      - name: ‚òïÔ∏è Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: üèó Build app for testing
        run: ./gradlew :app:assembleDebugAndroidTest

      - name: üß™ Build instrumential test
        run: ./gradlew :app:assembleInstrumentialTest

      - uses: actions/upload-artifact@v2
        with:
          name: apk
          path: |
            app/build/outputs/apk/instrumentialTest/
            app/build/outputs/apk/androidTest/debug/

  integration-tests:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: apk
          path: app

      - name: Debug
        run: |
          ls -R

      - name: Add permissions
        run: chmod +x .github/workflows/run_integration_tests.sh

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          disable-animations: true
          profile: Nexus 5X
          api-level: 28
          script: .github/workflows/run_integration_tests.sh io.novafoundation.nova.balances.BalancesIntegrationTest

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: anroid-results
          path: ./allure-results.tar

  report:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    if: always() && (needs.build.result == 'success')
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Unzip results
        run: |
          tar -xvf artifacts/anroid-results/allure-results.tar

      - uses: ./.github/workflows/report
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          keep-reports-history: 30

  alert:
    runs-on: ubuntu-latest
    needs: report
    if: always() && (needs.integration-tests.result == 'failure')
    env:
      GITHUB_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - uses: actions/checkout@v2
      - name: Report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Integration tests failed on ${{ github.ref }} branch

            Failed run:
            ${{ env.GITHUB_WORKFLOW_URL }}

            Report:
            https://improved-enigma-vryoz6l.pages.github.io/${{ github.run_number }}
